/**
 * Placeholder generation is no longer needed.
 * Real documents live in demo_docs/ (PDFs from Evoqua project 2034/001845).
 * Synthetic xlsx and docx are generated by scripts/gen-demo-docs.ts.
 *
 * Run: pnpm tsx scripts/gen-demo-docs.ts
 */
console.log('Real docs are in demo_docs/. Run `pnpm tsx scripts/gen-demo-docs.ts` to (re)generate the xlsx and docx.');
